# Generated by Django 2.1.2 on 2018-11-14 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essai1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_message',
            name='membre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='essai1.Membre'),
            preserve_default=False,
        ),
    ]
