# Generated by Django 2.1.2 on 2018-11-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essai1', '0002_f_message_membre'),
    ]

    operations = [
        migrations.AddField(
            model_name='f_sujet',
            name='accepter',
            field=models.BooleanField(default=False, verbose_name='Accepter la demande'),
        ),
    ]
