# Generated by Django 2.1.2 on 2018-11-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essai1', '0004_evenement_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='image',
            field=models.ImageField(upload_to='evenement/'),
        ),
    ]
