# Generated by Django 2.1.2 on 2018-11-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essai1', '0006_espacepresident_espacesecretaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'organisation")),
                ('lien', models.URLField(verbose_name='URL du site')),
            ],
        ),
    ]
