# Generated by Django 2.1.2 on 2018-11-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essai1', '0007_lien'),
    ]

    operations = [
        migrations.AddField(
            model_name='apropos',
            name='juri_membre',
            field=models.TextField(default=1, verbose_name='Combien de juridictions sont membres?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apropos',
            name='le_but',
            field=models.TextField(default=1, verbose_name='Quel est le but de Arinwa?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apropos',
            name='qui_peut_user',
            field=models.TextField(default=1, verbose_name='Qui peut utiliser ARINWA?'),
            preserve_default=False,
        ),
    ]
